name: Terraform Apply or Destroy RDS

on:
  workflow_dispatch:
    inputs:
      deployment:
        type: choice
        description: DeployOrTearDown
        options:
          - Apply
          - Destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  
jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: apply or destroy
        run: |
          if [ ${{ github.event.inputs.deployment }} == 'Apply' ]; then  
            terraform apply -auto-approve
          elif [ ${{ github.event.inputs.deployment }} == 'Destroy' ]; then  
            terraform destroy -auto-approve
          fi
        shell: bash


  